-- monthly_projects: 월별 작업자 선택용 프로젝트 목록
-- (이미 생성했다면 CREATE TABLE 부분은 건너뛰고 제약/초기화 테이블만 적용)

create table if not exists public.monthly_projects (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  month text not null,
  project_name text not null
);

-- 같은 월에 동일 프로젝트명 중복 방지
create unique index if not exists monthly_projects_month_project_name_uidx
  on public.monthly_projects (month, project_name);

-- 월 목록 초기화 여부 (행이 있으면 해당 월은 이미 생성됨 — 빈 목록도 재복사 금지)
create table if not exists public.monthly_project_months (
  month text primary key,
  created_at timestamptz not null default now()
);

-- 관리자 앱(anon)에서 읽기/쓰기 가능하도록 RLS 정책 예시
-- 프로젝트 정책에 맞게 조정하세요.
alter table public.monthly_projects enable row level security;
alter table public.monthly_project_months enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'monthly_projects'
      and policyname = 'monthly_projects_all_anon'
  ) then
    create policy monthly_projects_all_anon
      on public.monthly_projects
      for all
      to anon, authenticated
      using (true)
      with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'monthly_project_months'
      and policyname = 'monthly_project_months_all_anon'
  ) then
    create policy monthly_project_months_all_anon
      on public.monthly_project_months
      for all
      to anon, authenticated
      using (true)
      with check (true);
  end if;
end $$;
